#cloud-config
autoinstall:
  version: 1

  locale: pt_BR.UTF-8

  keyboard:
    layout: br
    variant: ""

  timezone: America/Sao_Paulo

  identity:
    realname: "Pablo Pablovich"
    username: pablo
    password: "$6$O9J16PHfuhUnG4Yc$97fY6ghpOMhkfK8SqjGt479pOXpCihJVWBKVbbBQJDw.HbF7ddY1LLzUDl5TyVq/513SdBsrpn4Mwwygdx0HQ/"
    hostname: mtlnx001

  storage:
    layout:
      name: lvm
    sizing-policy: all

  apt:
    geoip: true
    preserve_sources: false

  packages:
    - ubuntu-cinnamon-desktop
    - libreoffice

  shutdown: reboot
