#cloud-config
autoinstall:
  version: 1

  locale: pt_BR.UTF-8

  keyboard:
    layout: br
    variant: ""

  timezone: America/Sao_Paulo
  
  network:
    version: 2
    ethernets:
      all:
        match:
          name: "*"
        dhcp4: true

  identity:
    username: user
    password: "$6$RSfUJT7WiW2AdbDl$xrTaJz8FqeBQSt4mxpXy1EnMKForuhBR/ovAXSgB.gTpr75EzC6/BTLOTbkYK8n9h6pxBPUAVNQYoOK0VAlgu1"
    hostname: linux

  storage:
    layout:
      name: lvm
    sizing-policy: all

  apt:
    geoip: true
    preserve_sources: false

  shutdown: reboot
